
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between p-16">
          <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
            <div className="fixed left-0 top-0 flex w-full justify-center border-b border-blue-300 bg-gradient-to-b from-blue-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
              <ul className='list-inside'>
                <li className="hover:to-blue-900 hover:font-semibold hover:shadow"><Link href="/">Home</Link></li>
                <li className="hover:to-blue-900 hover:font-semibold hover:shadow"><Link href="/about">About</Link></li>
                <li className="hover:to-blue-900 hover:font-semibold hover:shadow"><Link href="/contact">Contact</Link></li>
                <li className="hover:to-blue-900 hover:font-semibold hover:shadow"><Link href="/movies">Movies</Link></li>
                <li className="hover:to-blue-900 hover:font-semibold hover:shadow"><Link href="/comments">Comments</Link></li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
